# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "127.0.0.1"
      MYSQL_ROOT_PASSWORD: "root"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080